version: "3"

env:
  PKR_VAR_region: us-east-2
  PKR_VAR_ami_name: eventstoredb-zfs-hardened
  AWS_DEFAULT_REGION: us-east-2

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Validate and build the AMI
    cmds:
      - task: validate
      - packer build eventstoredb-zfs-hardened.pkr.hcl

  validate:
    desc: Validate the Packer template
    cmds:
      - packer init .
      - packer validate eventstoredb-zfs-hardened.pkr.hcl

  build-force:
    desc: Force rebuild the AMI (ignores cache)
    cmds:
      - packer build -force eventstoredb-zfs-hardened.pkr.hcl

  fmt:
    desc: Format all Packer HCL files
    cmds:
      - packer fmt .

  clean:
    desc: Clean up plugin and build cache
    cmds:
      - rm -rf .packer.d/plugins
